# General
RESEARCH_EVAL_MAX_PARALLEL_WORKERS: 8
RESEARCH_EVAL_TIMEOUT: 10800  # 3 hour for Ray cluster jobs
RESEARCH_CODER_TIMEOUT_SECONDS: 7200 # at most 2 hour for each evaluation
RESEARCH_SCORE_DISPLAY_PRECISION: 8

# Production config
RESEARCH_EVAL_GPU_NUM: 1
RESEARCH_EVAL_CPU_NUM: 10
RESEARCH_STORAGE_BASE_PATH: /mnt/stephen/research_data # UPDATE HERE
