# Ovals eigenvalue-search task
RESEARCH_EVAL_MAX_PARALLEL_WORKERS: 8
RESEARCH_EVAL_TIMEOUT: 900
RESEARCH_SCORE_DISPLAY_PRECISION: 8

# Production config
RESEARCH_EVAL_GPU_NUM: 1
RESEARCH_EVAL_CPU_NUM: 10
